celo-org/faucet

package.json, src/celo-adapter.ts, yarn.lock
ensure we can always transfer stables if we have celo but exchanging celo for stable when needed. 
n/a
- #16 
yes
n/a
=> exchange CELO for stable if stable is out when fauceting

package.json, scripts/cli.ts, src/config.ts, src/database-helper.ts, src/utils.ts, yarn.lock
removes code for inviting phone numbers as this is deprecated generally and not working
=> remove old invite / escrow feature

apps/web/pages/index.tsx, apps/web/public/meta-mask-fox.svg, apps/web/src/faucet-status.tsx, apps/web/src/request-form.tsx, apps/web/src/setup-button.tsx, apps/web/styles/Form.module.css, apps/web/styles/Home.module.css
Add Metamask Logo
Re enable to faucet button on completion
=> Add Metamask Logo

apps/firebase/database-rules.bolt, apps/firebase/src/database-helper.ts, apps/web/pages/api/faucet.ts, apps/web/pages/index.tsx, apps/web/src/faucet-interfaces.ts, apps/web/src/faucet-status.tsx, apps/web/src/firebase-serverside.ts, apps/web/src/request-form.tsx, apps/web/styles/Form.module.css, apps/web/styles/Home.module.css
hypothesis: most requests only want CELO. 
solution: by default only CELO will be faucetted with an easy opt in to mento cStables faucetted too
Tested on faucet-staging
=> Default to CELO only

apps/firebase/src/celo-adapter.ts, apps/firebase/src/database-helper.ts
=> dont misleading log that token is being sent when it might not be

apps/firebase/src/celo-adapter.ts, apps/firebase/src/database-helper.ts, apps/firebase/src/index.ts
* fix phase out logic
* decrease max amount address can have and points at which phase down begins. 
* convert before sending to SAFE to avoid it failing when faucet is out
* Changes weekly filling of Dev Rel Faucet to be earlier in day so closer to time of epoch rewards
=> Big Faucet Modifcations

.husky/pre-commit, apps/firebase/src/database-helper.ts, apps/web/src/faucet-status.tsx, package.json, yarn.lock
A misplace comma made it to main branch, :(
so i added pre commit hook for linting
fixes some lint errors
This commit was pre linted
=> Add Commit Linting

apps/web/pages/index.tsx, apps/web/src/balance.ts, apps/web/src/faucet-status.tsx, apps/web/src/request-form.tsx, apps/web/styles/Form.module.css, apps/web/styles/Home.module.css, apps/web/styles/globals.css
adds a banner when the faucet is closed for the day
* disabled button no longer has hover effect that looks active
yep 
- Fixes
=> show a banner when faucet does not have enough CELO to FAUCET

apps/firebase/scripts/cli.ts, apps/firebase/src/database-helper.ts, apps/firebase/src/index.ts, apps/web/pages/index.tsx, apps/web/src/faucet-status.tsx, apps/web/src/request-form.tsx, apps/web/src/setup-button.tsx
Faucet has been drained consistently. To remedy this we start with topping up celo hourly and reducing amount sent out. 
* Adds an hourly job to top up CELO from the cEUR balance.
* Next deploy will reduce the standard amount to 2.5 Tokens
part of https://github.com/celo-org/faucet/issues/46
=> Constant refill

apps/firebase/src/celo-adapter.ts
Adds fallbacks in case using the broker contract fails
=> Add fallbacks for missing Broker contract

apps/web/pages/[chain].tsx, apps/web/src/faucet-interfaces.ts, apps/web/src/setup-button.tsx
Adds Cannoli config to the MetaMask setup button
=> Adds Cannoli config to metamask setup

renovate.json
fixes invalid schedule for renovate
- Fixes #123
=> fix config for renovate

.github/workflows/ci.yaml, apps/firebase/src/celo-adapter.ts
adds basic CI checks runner. 
* install
* lint
* check that renovate config is not messed up!
=> add a basic ci runner

apps/web/package.json, package.json
This PR specifies default node version for all the apps.
None.
Tested locally.
Backwards compatible as it just specifies the current state of things.
=> Specify default version of node to 18

apps/web/package.json, yarn.lock
Fixes a bug where clicking "Faucet" button resulted in an error. It was caused by using two different firebase versions in the project. Unifying required version fixed the issue.
None.
Tested locally.
=> Fix fauceting error

apps/web/config/chains.ts
Add Dango Blockscout link to generate a valid tx link on faucet success for Dango.
=> Add Dango Explorer URL

apps/firebase/src/database-helper.ts
This PR fixes stable tokens transfers by running them sequentially.
=> Fix transfers

apps/web/utils/balance.ts
This PR fixes issue with fetching the balance.
None.
Ran locally.
=> Change base API URL

apps/web/components/faucet-status.tsx, apps/web/config/chains.ts, apps/web/types/index.ts
This PR removes support for Dango.
=> Remove Dango

.github/workflows/deploy-chain.yaml
Testing workload identity federation authentication to firebase.
=> test new auth workflow

.github/workflows/deploy-chain.yaml
missed that the rpc url is set on the network
=> config was not set correctly

.github/workflows/deploy-chain.yaml
Fix service account conditional to deploy to different sa for staging/prod
=> correct conditional for service account

.github/workflows/deploy-chain.yaml
Add a conditiona to use the proper workload identity provider for staging instead of master.
=> fix workload identyt provider conditional for prod/staging

apps/web/utils/firebase.serverside.ts
=> fix: expire the hash key in 24hrs everytime

apps/web/pages/api/faucet.ts, apps/web/utils/firebase.serverside.ts
[Closes #253]
I did the limit per hour rather than per day, felt more natural? let me know if it needs be changed
=> feat: add global rate limiting and github email limits
